spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: creditbanknotifications@gmail.com
    password: rldm ggvm oqma rgsv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
