spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deal
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          format_sql: true
        show_sql: true